/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_H_RPCGEN
#define _FILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct number {
	float x;
	float y;
};
typedef struct number number;

#define ADD_PROG 0x2CCCCCCC
#define ADD_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  float * add_1(number *, CLIENT *);
extern  float * add_1_svc(number *, struct svc_req *);
#define substract 2
extern  float * substract_1(number *, CLIENT *);
extern  float * substract_1_svc(number *, struct svc_req *);
#define multi 3
extern  float * multi_1(number *, CLIENT *);
extern  float * multi_1_svc(number *, struct svc_req *);
#define div 4
extern  float * div_1(number *, CLIENT *);
extern  float * div_1_svc(number *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  float * add_1();
extern  float * add_1_svc();
#define substract 2
extern  float * substract_1();
extern  float * substract_1_svc();
#define multi 3
extern  float * multi_1();
extern  float * multi_1_svc();
#define div 4
extern  float * div_1();
extern  float * div_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_number (XDR *, number*);

#else /* K&R C */
extern bool_t xdr_number ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_H_RPCGEN */
