/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file.h"

float *
add_1_svc(number *argp, struct svc_req *rqstp)
{
	static float  result;

	result= argp->x + argp->y;
	return &result;
}

float *
substract_1_svc(number *argp, struct svc_req *rqstp)
{
	static float  result;

	result= argp->x - argp->y;

	return &result;
}

float *
multi_1_svc(number *argp, struct svc_req *rqstp)
{
	static float  result;

	result= argp->x * argp->y;

	return &result;
}

float *
div_1_svc(number *argp, struct svc_req *rqstp)
{
	static float  result;

	result= argp->x / argp->y;

	return &result;
}
